### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by depl0y** [emaloney/CleanroomLogger#10]
I would love to see Cocoapods support for this.

**Comment by emaloney** [comment]
I have no objection to Cocoapods support.

I use Cocoapods quite a bit in my ObjC-based projects, and I love it. However, I've also found I haven't needed it in a Swift-only, post-iOS 8 world where we can vend our own frameworks.

I'm unlikely to have time to add Cocoapods support in the short-term, and while I'll entertain pull requests, I'm not inclined to merge in Cocoapods support until I address [Issue #11](https://github.com/emaloney/CleanroomLogger/issues/11) by creating a script to automate the process of releasing new versions. I'll want to be sure that such a script integrates with Cocoapods so that the release process isn't complicated by the addition of support for another dependency manager.

**Comment by jlaws** [comment]
+1

**Comment by mmarkov-appolica** [comment]
+1

**Comment by ralito** [comment]
+1

**Comment by lisi1987** [comment]
+1

**Comment by archfear** [comment]
+1

**Comment by neil-wu** [comment]
+1

**Comment by leetal** [comment]
+1

**Comment by jwardle** [comment]
+1

**Comment by dhonig** [comment]
+1 Is it really that hard to get this into CocoaPods  should be an afternoon and not more eh?

**Comment by emaloney** [comment]
It's not hard; I just don't need it myself, and given the rest of my workload, it's not a priority.

Pull requests will be considered.

**Comment by intere** [comment]
+1

**Comment by cday** [comment]
+1

**Comment by tomasKa** [comment]
+1

**Comment by emaloney** [comment]
I've been spending a bit of time working on this recently, and it turns out it's a pretty big job.

The underlying issue is that the ASL dependency is not exposed to Swift. When building in Xcode, we solve this problem with a bridging header, but if you try to build using Cocoapods, a bridging header can't be used to pull in a dependency for a framework.

Instead, you need to manually construct Swift module map files for each potential platform and architecture ([see here](https://github.com/soffes/Crypto/tree/master/CommonCrypto) for an example of what this looks like). However, once you do this, things become infinitely more complicated; Cocoapods only lets you specify settings by platform, so there's no way to specify a setting based on processor architecture.

Because supporting Cocoapods would require wholesale reworking of the existing build system, and because I've never been a big fan of the violence Cocoapods does to Xcode project files, I'm not going to be adding Cocoapods support.

Carthage works well for Swift frameworks, and I've already added support for the up-and-coming Swift Package Manager (which at the moment is only helpful on OS X since SPM can't build for other platforms yet).

Frankly, with the direction that Swift is going in, Cocoapods is not a good long-term option because it's tied to Xcode and can therefore never work on non-Apple platforms.

So, I'm not going to be adding Cocoapods support.

**Comment by jshier** [comment]
@emaloney It appears that `import asl` is now works in Swift 3, so I think this decision could be reconsidered for the Swift 3 version of the library. However, ASL is now pretty much entirely deprecated for macOS 10.12 and iOS 10, so you may want to rearchitect for those platforms anyway.

**Comment by emaloney** [comment]
As [discussed in another thread](https://github.com/emaloney/CleanroomLogger/issues/69#issuecomment-284852205), I can now state definitively that we will never be adding Cocoapods support to CleanroomLogger.
