### ISSUE TITLE
Deployment Target Unset

### ISSUE THREAD

**Issue by SandyChapman** [emaloney/CleanroomLogger#40]
It looks like the deployment target is not set for both the CleanroomLogger and CleanroomLoggerASL projects. Is there a reason for this? Since this is intended to be deployed as a Swift Framework, wouldn't it make sense to set this to 8.0 (at least for iOS)?

**Comment by emaloney** [comment]
Hi Sandy,

The deployment target is set to 8.0 for iOS, but it's not being done in the typical way.

Within our Cleanroom projects, we're setting the deployment target via the `.xcconfig` files found within `BuildControl/config`. You can reveal where the setting is coming from by selecting the "Levels" option within the Xcode build settings. Here's the one for iOS for example:

![screen shot 2016-01-29 at 12 28 30 pm](https://cloud.githubusercontent.com/assets/3768925/12682915/05a29b3a-c684-11e5-8154-8d3e3b8a9af3.png)

Although Xcode shows the setting coming from `Debug-iOS.xcconfig`, it is actually found within a file included by that: `iOS.xcconfig`. This file looks like:

```
SDKROOT = iphoneos
IPHONEOS_DEPLOYMENT_TARGET = 8.0
ENABLE_BITCODE = YES
BITCODE_GENERATION_MODE = bitcode
```

We do it via files so we can easily update our settings with scripts, rather than by manually twiddling settings in the Xcode interface.

Hope this explanation helps,
E.

**Comment by SandyChapman** [comment]
Thanks for the explanation.
