### ISSUE TITLE
Support for Swift 2.3 / Swift 3

### ISSUE THREAD

**Issue by lukaskubanek** [emaloney/CleanroomLogger#48]
Hi @emaloney!

I'd like to ask about the plan for updating this library (and its dependency [CleanroomASL](https://github.com/emaloney/CleanroomASL)) to work with Swift 2.3 or Swift 3 respectively?

Are you going to explicitly update the underlying architecture to leverage the new logging mechanism introduced at WWDC 2016?

**Comment by emaloney** [comment]
Hi @lukaskubanek,

As of now, both CleanroomASL and CleanroomLogger have a `swift2.3` and `swift3` branch. These branches will compile using the Xcode 8 betas.

Eventually, the CleanroomASL dependency will be split out so that it is no longer required for CleanroomLogger. You will still be able to use CleanroomASL as the underlying logging engine if you wish, but the base implementation of CleanroomLogger will be updated to use [the new logging engine](https://developer.apple.com/reference/os/1891852-logging) that Apple announced at WWDC.

E.

**Comment by lukaskubanek** [comment]
Thanks so much for the update and the clarification about the direction of further development!
