### ISSUE TITLE
CleanroomBase dependency

### ISSUE THREAD

**Issue by jberkel** [emaloney/CleanroomLogger#5]
I like the approach of the framework but is the base dependency really needed? A "light-weight" logging library should be self-contained and not depend on another project. If I want to use CleanroomLogger I have to pull in code which is actually not needed/used.

**Comment by emaloney** [comment]
Lightweight in this case refers to the design of CleanroomLogger engine.

Is your primary objection to the fact that multiple frameworks are produced by the build process? Or the fact that the CleanroomBase framework contains some code not in use by CleanroomLogger?

We have been toying with the idea of splitting up CleanroomBase. The upside would be shipping without some code not currently used by CleanroomLogger or CleanroomASL but at the potential expense of needing to integrate even more frameworks. 

(Swift doesn't seem to allow multiple modules per framework, so that's a bit of a constraint on how integration proceeds given that were using frameworks.)

We're still getting used to this world of framework-based packaging so please bear with us while we find the optimal balance. Your input will help.

**Comment by jberkel** [comment]
I have a problem with both points - integrating three frameworks (all of them required) is cumbersome and seems excessive for a logging framework. While I understand the idea of splitting ASL/Core from a dev perspective I don't think the users of a logging framework should have to care about all these details. And then there's also unneeded code pulled in with CleanroomBase (which is almost as big as ASL+Core combined).

Wouldn't it be possible to pull in Base + ASL as static libs, so that the linker can strip out unused code? This way only one framework is exposed to the user. I don't mean to abandon frameworks completely, just add an additional static lib target which can be linked from the core project.

**Comment by emaloney** [comment]
CleanroomBase will be removed as a dependency in the next release, so there will only be 2 frameworks to deal with instead of three.

As for CleanroomASL, for the time being, it will continue to exist as a separate framework. However, I'm looking into the feasibility of simplifying the packaging further without going the static linking route.

**Comment by emaloney** [comment]
Thanks for taking the time to share your ideas. As of the latest release, the CleanroomBase dependency is gone. (And as a result, I'll be closing this ticket.)

There may be some improvements to Swift frameworks coming at WWDC that would allow integrating a single framework for CleanroomLogger without static linking, which I'm trying to avoid. I agree that it would be ideal to provide the simplest integration possible.

**Comment by jberkel** [comment]
Great, I'll have another look at integrating the library then.
