### ISSUE TITLE
swift2.3:  Product->Archive:   error: use of unresolved identifier 'Log'  

### ISSUE THREAD

**Issue by Jiar** [emaloney/CleanroomLogger#58]
I use CleanroomLogger 2.2.0(First Swift 2.3 / Xcode 8 release) in Xcode project

when I archive :
error: use of unresolved identifier 'Log'

**Comment by emaloney** [comment]
Does this *only* happen when archiving? Are you able to build successfully?

If building works but archiving doesn't, can you test whether compiling a Release build works?

Usually when I see problems that occur only during archiving, it's because (1) my "normal" builds are Debug builds, but my archive builds are Releases, and (2) the dependencies and linked frameworks differ between Debug and Release.

I suspect it's the configuration of your Xcode project. If you can provide me with any additional information, it might help.

**Comment by emaloney** [comment]
Closing for lack of response.
