### ISSUE TITLE
Custom logger wrapper not showing correct line number

### ISSUE THREAD

**Issue by wongzigii** [emaloney/CleanroomLogger#78]
So far I had created a custom logger wrapper, so I call `QLog.info()` where I want. So far so good, However, the console keeps showing the line number of my wrapper:

![wx20170428-173327](https://cloud.githubusercontent.com/assets/7384288/25523308/c6b46482-2c38-11e7-9ffd-e77952f1eb85.png)

Here is my warpper:

````swift
import CleanroomLogger

struct QLog {
    
    static let shared = QLog()
    
    static func setup() {
        CleanroomLogger.Log.enable()
        
        self.info("CleanroomLogger is now enable!")
    }
    
    static func error(_ text: String) {
        CleanroomLogger.Log.error?.message(text)
    }
    
    static func debug(_ text: String) {
        CleanroomLogger.Log.debug?.message(text)
    }
    
    static func warning(_ text: String) {
        CleanroomLogger.Log.warning?.message(text)
    }
    
    static func verbose(_ text: String) {
        CleanroomLogger.Log.verbose?.message(text)
    }
    
    static func info(_ text: String) {
        CleanroomLogger.Log.info?.message(text)
    }
}
````

Is this an expected behavior?

**Comment by emaloney** [comment]
Yes, this behavior is expected because CleanroomLogger shows the source file and line number of the call site—the place where you call a function like `message()`, `trace()` or `value()`.

However, you can modify your code to capture the source file and line number where your wrapper is called and pass that along to CleanroomLogger.

If you look at [the declaration for the `message()` function](https://github.com/emaloney/CleanroomLogger/blob/master/Sources/LogChannel.swift#L93):

```swift
public func message(_ msg: String, function: String = #function, filePath: String = #file, fileLine: Int = #line)
```

you'll notice the `function`, `filePath` and `fileLine` parameters with default values. Normally you don't provide these values, but this is how CleanroomLogger figures out where it is being called from.

You can use the same technique in your wrapper to pass down the appropriate values.

For example, your `error()` function could be rewritten as:

```swift
static func error(_ text: String, function: String = #function, filePath: String = #file, fileLine: Int = #line) {
    CleanroomLogger.Log.error?.message(text, function: function, filePath: filePath, fileLine: fileLine)
}
```

Then, you'll see the call site you expect when you call `QLog.shared.error()`. *And you won't need to modify any of the callers of your `QLog` functions; the magic of default parameter values takes care of everything for you.*

Hope this helps,
E.

**Comment by wongzigii** [comment]
Thanks so much!
