### ISSUE TITLE
How can I make the log output shorter?

### ISSUE THREAD

**Issue by zoul** [emaloney/CleanroomLogger#79]
The default log output is too long for us:

    2017-05-15 09:19:57.387123+0200 xctest[15432:64590545] [CleanroomLogger]

This prefix is quite spammy in the console, adding little useful information. Is it possible to cut it down? A time stamp would be great.

**Comment by emaloney** [comment]
Hi zoul,

The prefix is added by Apple's `os_log()` function by default. You can configure CleanroomLogger to bypass `os_log()`, which will avoid having that prefix added. ([This is explained in little bit more detail here](https://github.com/emaloney/CleanroomLogger#xcodelogconfiguration).)

How you do that exactly depends on how you're configuring CleanroomLogger. If you're using the `XcodeLogConfiguration`, you may want to look into using its superclass [`ConsoleLogConfiguration`](https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/API/Classes/ConsoleLogConfiguration.html) instead, since the `XcodeLogConfiguration` is designed to mimic `os_log()` by default, even when it is not in use.

You will want to provide [`.useExclusively`](https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/API/Classes/ConsoleLogConfiguration/StandardStreamsMode.html#/s:FOC15CleanroomLogger23ConsoleLogConfiguration19StandardStreamsMode14useExclusivelyFMS1_S1_) as the value for the `stdStreamsMode` initializer argument to bypass `os_log()`. If you're using `ConsoleLogConfiguration`, that's all you'll need to do to get rid of that prefix. If you're using `XcodeLogConfiguration`, you will also need to pass `false` for the `mimicOSLogOutput` argument.

Because `ConsoleLogConfiguration` is a little more flexible, you can pass it one or more `LogFormatters`, to add the timestamp you want to add. The [`FieldBasedLogFormatter`](https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/API/Classes/FieldBasedLogFormatter.html) gives you a very simple way to specify this. There is ample documentation on custom formatting. [This link gives an example](https://github.com/emaloney/CleanroomLogger#easy-mix-and-match-formatting), while [this one provides pointers](https://github.com/emaloney/CleanroomLogger#customized-log-formatting) to more in-depth explanations.

Hope this helps,
E.

**Comment by zoul** [comment]
Great answer, thank you very much!
